### PR TITLE
Use new CRS functionality provided by stm32f0xx-hal

### PR DESCRIPTION
**Pull request by therealprof**
Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by Disasm** [comment]
Thanks! Could you also update `stm32f0xx-hal` version in `Cargo.toml`?

**Comment by therealprof** [comment]
Shouldn't be necessary since it's just a new patch version. Unless someone has the old version locked in Cargo.lock that is.

**Comment by Disasm** [comment]
> Unless someone has the old version locked in Cargo.lock that is.

Yep, that's what I worry about.

**Comment by therealprof** [comment]
I did a `cargo upgrade` but it decided not to touch Cargo.toml.

**Comment by therealprof** [comment]
Ah, missed the error message:
```
# cargo upgrade
Command failed due to unhandled error: Failed to get new version

Caused by: The crate `cdc_acm` could not be found on crates.io.
Caused by: https://crates.io/api/v1/crates/cdc_acm: Client Error: 404 Not Found
```

**Comment by Disasm** [comment]
Thanks!

**Pull request merged**
